# Workflow name
name: pai workflow

# Define the trigger event(s)
on: 
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "**"

# Jobs run in parallel by default, each runs steps in sequence
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # -
        # # 1: Login to Docker Hub (Optional)
        # name: Login to Docker Hub (Optional)
        # uses: docker/login-action@v3
        # with:
        #   username: ${{ vars.DOCKERHUB_USERNAME }}
        #   password: ${{ secrets.DOCKERHUB_TOKEN }} 

      -
        # 2: Checkout code
        name: Checkout code
        uses: actions/checkout@v3

      -
        # 3: Set up Docker for use in the workflow
        name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v3

      -
        # 4: Build Docker image
        name: Build Docker Image
        run:  |
          docker build --no-cache -t pai-build-env -f ./ci-cd-tools/Dockerfile .
        
      - 
        # If previous step fails
        name: Run on build docker failure
        if: failure()
        run: echo "Docker Image failed to build."

      -
        # 5: Run the Docker container
        name: Run Docker container
        run:  |
          docker run --name pico_build_container pai-build-env
      - 
        # If previous step fails
        name: Run on run docker failure
        if: failure()
        run: echo "Docker Container failed to run."

      -
        # 6: Copy out .uf2 file (change the uf2 filename [blink_rtos.uf2] to yours)
        name: Copy out .uf2 file
        run:  |
          docker cp pico_build_container:/root/powerlabs/folder/build/arm/embedded_devops_template.uf2 ./arm_build.uf2

      -
        # 7: Upload .uf2 file as artifact
        name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: arm_build-uf2
          path: ./arm_build.uf2

      -
        # 8: Remove the Docker container
        name: Remove Docker Container
        run: |
          docker rm pico_build_container

      # - 
      #   # 9: Push to release when with tag
      #   name: Push to release
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     files: arm_build.uf2
      #     body_path: BUILD.md 

      # -
      #   # 10: Push Docker image to Docker Hub (Optional)
      #   name: Push Docker image to Docker Hub (Optional)
      #   run: |
      #     docker tag pico_build_container my-dockerhub-user/pico_build_container:latest
      #     docker push my-dockerhub-user/pico_build_container:latest
